name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    # - name: Install Wine
    #   run: |
    #     sudo dpkg --add-architecture i386
    #     sudo apt update
    #     sudo apt install -y wine64 wine32

    - name: Electron Build for Linux
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run dist

    - name: Upload Linux Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-build-artifacts-linux
        path: dist-electron/

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    - name: Electron Build for Windows
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run dist

    - name: Upload Windows Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-build-artifacts-windows
        path: dist-electron/
